dependents:
  - "test-template-*-sync" # include
additional:
  - "g3w-client-plugin-*-template" # include
files:
  - ".gitignore"  # include
  - "!README.md" # exclude
   # you probably want to exclude these files:
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
